### ISSUE TITLE
代理的方式相对受限，能否支持修改OpenAI API Base URL呢

### ISSUE THREAD

**Issue by pengmaochang** [c121914yu/FastGPT#1]
OpenAI API Base URL默认是https://api.openai.com，但是如果找一台能访问外网的服务器A，代理该网址。然后让本地项目的OpenAI API Base URL设置为服务器A中的网址，即可实现本地服务器无缝访问。目前这种部署方式在国内较为流行，github上也有很成熟的无脑式部署教程，如下：
https://github.com/Ice-Hazymoon/openai-scf-proxy。

故，建议支持修改OpenAI API Base URL

**Comment by c121914yu** [comment]
后面会直接部署到国外服务器，

**Comment by summerbuild** [comment]
直接修改/app/node_modules/openai/dist/base.js里面的域名，在启动docker的时候用-v映射进去
