### ISSUE TITLE
V2 对话接口返回格式与 openai 的接口不符

### ISSUE THREAD

**Issue by ccyuvin** [c121914yu/FastGPT#107]
![image](https://github.com/c121914yu/FastGPT/assets/85599321/69f51a4a-119c-438f-93e3-fa7502dd9777)
openai官方接口 message 字段不是一个数组
![image](https://github.com/c121914yu/FastGPT/assets/85599321/5df3df23-17ff-4fd5-b1c4-ab7be56604dd)
fastgpt message 字段 返回的是一个数组。
版本v3.9.2
这在某些程序上是致命的。需要改写代码。希望能完全兼容。

**Comment by c121914yu** [comment]
感谢你的纠正。没有注意到这个错误。已经修复这个问题，推送待main，线上会在晚上同步更新
