### ISSUE TITLE
有现成的docker image下载吗?编译老通不过啊。

### ISSUE THREAD

**Issue by ramboma** [c121914yu/FastGPT#19]
希望往dockerhub上传一份,便与国内网络不好的兄弟下载学习

**Comment by c121914yu** [comment]
有的，docker-compose里那个镜像就是

**Comment by xiao-jay** [comment]
如果没梯子，怎么本地调用openai的接口调试呢

**Comment by xiao-jay** [comment]
@ramboma 现在github上面有打包的最新的fast-gpt image，https://github.com/c121914yu/FastGPT/pkgs/container/fast-gpt
@c121914yu 这个issue可以关闭了？

**Comment by ramboma** [comment]
可以了，谢谢

**Comment by ramboma** [comment]
可以了
