### ISSUE TITLE
无法导入模型数据

### ISSUE THREAD

**Issue by AntonRuan** [c121914yu/FastGPT#2]
提示：没有需要生成 【向量】 的数据

**Comment by c121914yu** [comment]
请提供具体操作步骤和截图。
这个提示是因为生成向量的函数中，没有从redis中获取到一个status = waiting 的数据，从而结束递归。请检查redis中是否存在该数据

**Comment by AntonRuan** [comment]
# 索引
# FT.CREATE idx:model:data ON JSON PREFIX 1 model:data: SCHEMA $.modelId AS modelId TAG $.dataId AS dataId TAG $.vector AS vector VECTOR FLAT 6 DIM 1536 DISTANCE_METRIC COSINE TYPE FLOAT32
# FT.CREATE idx:model:data:hash ON HASH PREFIX 1 model:data: SCHEMA modelId TAG dataId TAG vector VECTOR FLAT 6 DIM 1536 DISTANCE_METRIC COSINE TYPE FLOAT32
FT.CREATE idx:model:data ON HASH PREFIX 1 model:data: SCHEMA modelId TAG userId TAG q TEXT text TEXT vector VECTOR FLAT 6 DIM 1536 DISTANCE_METRIC COSINE TYPE FLOAT32


我看到您这边是注释了两行，我把最后一行输入redis-cli，程序是运行会报msg: idx:model:data:hash: no such index。于是我把第二行输入，最后导入数据就出现：没有需要生成 【向量】 的数据

**Comment by AntonRuan** [comment]
hgetall model:data:mz9g9kxuyooi
 1) "userId"
 2) "642e94dbe4ec04e75ef1fdfb"
 3) "modelId"
 4) "642e9e4cf75ebeb9b776b0ad"
 5) "q"
 6) "1"
 7) "text"
 8) "1"
 9) "status"
10) "waiting"

**Comment by dmSeven** [comment]
索引需要加个status字段：
FT.CREATE idx:model:data:hash ON HASH PREFIX 1 model:data: SCHEMA modelId TAG userId TAG status TAG q TEXT text TEXT vector VECTOR FLAT 6 DIM 1536 DISTANCE_METRIC COSINE TYPE FLOAT32

**Comment by c121914yu** [comment]
> # 索引
> # FT.CREATE idx:model:data ON JSON PREFIX 1 model:data: SCHEMA 
> .
> �
> �
> �
> �
> �
> �
> �
> �
> �
> �
> �
> �
> �
> �
> �
> �
> �
> �
> �
> .dataId AS dataId TAG $.vector AS vector VECTOR FLAT 6 DIM 1536 DISTANCE_METRIC COSINE TYPE FLOAT32
> # FT.CREATE idx:model:data:hash ON HASH PREFIX 1 model:data: SCHEMA modelId TAG dataId TAG vector VECTOR FLAT 6 DIM 1536 DISTANCE_METRIC COSINE TYPE FLOAT32
> FT.CREATE idx:model:data ON HASH PREFIX 1 model:data: SCHEMA modelId TAG userId TAG q TEXT text TEXT vector VECTOR FLAT 6 DIM 1536 DISTANCE_METRIC COSINE TYPE FLOAT32
> 
> 我看到您这边是注释了两行，我把最后一行输入redis-cli，程序是运行会报msg: idx:model:data#️⃣ no such index。于是我把第二行输入，最后导入数据就出现：没有需要生成 【向量】 的数据

注释的两行是不需要的了，只需要使用最后一行命令去创建索引

**Comment by c121914yu** [comment]
非常抱歉，我加了status索引，忘记在这边更新命令了

**Comment by c121914yu** [comment]
完整的部署流程已经发布到main的README.md

**Comment by AntonRuan** [comment]
👍
