### ISSUE TITLE
mac下启动,页面无法访问

### ISSUE THREAD

**Issue by gg159753** [c121914yu/FastGPT#28]
执行pmpn dev命令后  访问localhost:3000   页面一直在加载 无响应。  telnet能通
<img width="584" alt="image" src="https://github.com/c121914yu/FastGPT/assets/17918244/a7b48e16-6914-4ddf-bb77-9916214e691f">

<img width="510" alt="image" src="https://github.com/c121914yu/FastGPT/assets/17918244/43389187-b50e-4f0e-aace-b1c218d035d3">

**Comment by c121914yu** [comment]
少部分mac有这个问题，目前没找到原因

**Comment by xiao-jay** [comment]
是intel版本的mac还是m1 mac，可以给出更多信息吗

**Comment by gg159753** [comment]
1. m2、m1 pro  试了都存在这个问题 。docker方式启动也一样的问题。

2.浏览器调试模式下无报错/控制台无报错。 就是加载一直是pending
<img width="783" alt="image" src="https://github.com/c121914yu/FastGPT/assets/17918244/99ebba8c-81bc-4921-9d97-ca75487bc46f">

3. $ node --version
v14.20.1

**Comment by xiao-jay** [comment]
我的也是mac m1，可以正常运行，我的node version是,试试先升级一下node版本和各个依赖的版本
```
➜  FastGPT git:(main) ✗ node --version
v19.6.0
➜  FastGPT git:(main) ✗ pnpm -v
8.3.1
```

**Comment by gg159753** [comment]
nodejs升级到v19.6.0   能打开了
