### ISSUE TITLE
能否将对话窗口免登录独立使用？

### ISSUE THREAD

**Issue by 437153** [c121914yu/FastGPT#30]
有一种场景：创建了知识库，给普通用户使用时，她们不需要登录到这个平台，直接对话窗口使用即可。谢谢！

**Comment by c121914yu** [comment]
有过想法，但是安全设计还没到位，容易造成免密接口被刷

**Comment by 437153** [comment]
访问聊天界面，加一个访问密码呢？希望能看到这个功能，做好了知识库以后可以给员工去了解公司的产品。

**Comment by c121914yu** [comment]
> 访问聊天界面，加一个访问密码呢？希望能看到这个功能，做好了知识库以后可以给员工去了解公司的产品。

是个好方法。近期会加入改功能

**Comment by c121914yu** [comment]
v3.6已加入该功能
