### ISSUE TITLE
增加提示词的来源信息显示。

### ISSUE THREAD

**Issue by imseon** [c121914yu/FastGPT#32]
知识库的训练数据来源，通常都会是来自外部的文档。
可能是notion、飞书、或者本地的word文件。
这样，如果给出的回答不够准确或者全面，就可以跳转到源文档去查看更完整的信息。
因为目前的知识库，已经给出了响应的提示词，但提示词目前并没有跟信息源做关联。所以是否会考虑增加这个关联。
如果愿意考虑的话，那我可以提一个PR来实现这个功能。
目前的思路，就是导入知识库的时候，临时记录一个来源，等到拆分完成后，将来源以一个特殊的字符串格式，保存到知识库中。
这样，每次响应的时候，就可以从提示词中解析出来源来渲染到页面上。

大家觉得如何呢？

**Comment by c121914yu** [comment]
你可以手动填写文档链接。模型会回复链接的

**Comment by c121914yu** [comment]
你可以手动填写文档链接。模型会回复链接的

**Comment by c121914yu** [comment]
非常感谢你的提议。来源引用是确实是一个重要的内容。但是对于本地文件直接上传，我们没有对文件进行存储，这块存储的成本非常高。

另外，知识库结构近期会做一次调整。知识库模块会独立出来，不再绑定模型，而是模型选择知识库。

如果你对这个项目感兴趣，想参与开发，欢迎加入开发者群。

**Comment by c121914yu** [comment]
已增加来源，包含3类。
手动导入，手动修改和文件名。
