### ISSUE TITLE
api上下文是不是没有生效

### ISSUE THREAD

**Issue by pizixi** [c121914yu/FastGPT#34]
网页有上下文，但是通过api调用，上下文貌似没有生效

**Comment by c121914yu** [comment]
api是一个数组，你需要全部传进来

**Comment by pizixi** [comment]
照着api文档上如下传的，貌似没啥用
"prompts": [
        {
            "obj": "System", 
            "value": "下面是 AI 和 Human 的对话，讨论 laf 的内容。"
        },
        {
            "obj": "Human", 
            "value": "什么是 laf"
        },
        {
            "obj": "AI", 
            "value": "laf 是云开发平台...."
        },
        {
            "obj": "Human", 
            "value": "laf 可以做什么?"
        },
    ]

**Comment by pizixi** [comment]
另外请问下大佬，是否可以增加配置openai反向代理url的设置，目前看只能配置openaiKey

**Comment by c121914yu** [comment]
> 另外请问下大佬，是否可以增加配置openai反向代理url的设置，目前看只能配置openaiKey

已经有了。base url

**Comment by c121914yu** [comment]
> 照着api文档上如下传的，貌似没啥用
> "prompts": [
>         {
>             "obj": "System", 
>             "value": "下面是 AI 和 Human 的对话，讨论 laf 的内容。"
>         },
>         {
>             "obj": "Human", 
>             "value": "什么是 laf"
>         },
>         {
>             "obj": "AI", 
>             "value": "laf 是云开发平台...."
>         },
>         {
>             "obj": "Human", 
>             "value": "laf 可以做什么?"
>         },
>     ]

给实际请求内容，我们测试是可以的。
