### ISSUE TITLE
邮箱注册失败报错：Operation `auth_codes.findOne()` buffering timed out after 10000ms

### ISSUE THREAD

**Issue by xianyu110** [c121914yu/FastGPT#36]
Operation `auth_codes.findOne()` buffering timed out after 10000ms

求大佬解答
![image](https://github.com/c121914yu/FastGPT/assets/53889513/f599fec2-30f4-47bf-90c6-254e7ea1845f)

**Comment by c121914yu** [comment]
检查mongo数据库是否正常。以及项目环境变量是否对应数据库
