### ISSUE TITLE
有考虑使用vercel一键部署吗？

### ISSUE THREAD

**Issue by yuhao1118** [c121914yu/FastGPT#37]
看到整体技术栈是基于next.js开发的，vercel对这块儿的支持力度比较大。唯一需要考虑的是数据存储。现阶段使用的似乎是mongodb，有两个选择
  1. 使用第三方的mongodb（可能需要收费）
  2. 迁移到postgresql。vercel和neon都提供了免费的postgresql服务，可以白嫖。同时看到知识库数据也是使用postgresql，可以考虑合并，统一使用一个数据库？

**Comment by yuhao1118** [comment]
刚开始看项目代码，还不够熟悉。希望作者能看下我的理解是否正确，十分感谢。如果没问题，我可以来做vercel部署这块儿的工作。

**Comment by c121914yu** [comment]
目前不计划。6月会迁移到sealos集群，包括数据库。

**Comment by c121914yu** [comment]
数据库不会合并。个人不喜欢写sql，更喜欢mongo的轻便灵活。

**Comment by callzhang** [comment]
作者有考虑使用向量数据库吗？

**Comment by c121914yu** [comment]
> 作者有考虑使用向量数据库吗？

pg vector就类似向量数据库

**Comment by aehyok** [comment]
> 数据库不会合并。个人不喜欢写sql，更喜欢mongo的轻便灵活。

感觉大佬 可以尝试一下，没什么难度 ，如果需要我可以帮忙写sql相关的

**Comment by c121914yu** [comment]
> > 数据库不会合并。个人不喜欢写sql，更喜欢mongo的轻便灵活。
> 
> 感觉大佬 可以尝试一下，没什么难度 ，如果需要我可以帮忙写sql相关的

必然不会尝试。sql太反人类了，而且mongo的维护成本和功能在这个项目都优于sql

**Comment by aehyok** [comment]
> > > 数据库不会合并。个人不喜欢写sql，更喜欢mongo的轻便灵活。
> > 
> > 
> > 感觉大佬 可以尝试一下，没什么难度 ，如果需要我可以帮忙写sql相关的
> 
> 必然不会尝试。sql太反人类了，而且mongo的维护成本和功能在这个项目都优于sql

好的，前端说出来可以，理解。哈哈

**Comment by c121914yu** [comment]
> > > > 数据库不会合并。个人不喜欢写sql，更喜欢mongo的轻便灵活。
> > > 
> > > 
> > > 感觉大佬 可以尝试一下，没什么难度 ，如果需要我可以帮忙写sql相关的
> > 
> > 必然不会尝试。sql太反人类了，而且mongo的维护成本和功能在这个项目都优于sql
> 
> 好的，前端说出来可以，理解。哈哈

😂毕竟monogo与node结合非常好。国内习惯spb+sql而已，mongo5后功能很可以的。
比如我做ip限流时候，没到百万时候都不需要用到redis。包括v4后可能需要临时存储各种类型中间结果，文本 文件 音频等，也不需要用到oss，直接往mongo存。
