### ISSUE TITLE
开发中的Open Api Key怎么使用？

### ISSUE THREAD

**Issue by noob3-3** [c121914yu/FastGPT#4]
开发中的Open Api Key怎么使用，没看到有使用的地方

**Comment by c121914yu** [comment]
环境变量OPENAIKEY

**Comment by czruby** [comment]
提示“请求次数太多了，请慢点~”怎么解决

**Comment by c121914yu** [comment]
> 提示“请求次数太多了，请慢点~”怎么解决

有可能是api的问题。openai里Too many request下还可能有几个错误。。。请检查下自己的api是否可以正常用

**Comment by noob3-3** [comment]
> 环境变量OPENAIKEY

也就说说我可以在您网站充钱，然后使用这个key去部署这个项目使用？

**Comment by c121914yu** [comment]
> > 环境变量OPENAIKEY
> 
> 也就说说我可以在您网站充钱，然后使用这个key去部署这个项目使用？

网站上充钱就不需要用key了，

**Comment by czruby** [comment]
> > 提示“请求次数太多了，请慢点~”怎么解决
> 
> 有可能是api的问题。openai里Too many request下还可能有几个错误。。。请检查下自己的api是否可以正常用

请问如何检查api是否可以正常使用？ChatGPT官方网站上登录是可以正常提问的。

**Comment by noob3-3** [comment]
我是说这个key
![image](https://user-images.githubusercontent.com/25631340/231351967-88eff5bb-89a4-499e-b1f5-8926c4bb6934.png)

**Comment by c121914yu** [comment]
这个key是允许你通过api调用平台上的功能。目前只开了知识库的接口，具体看上面的文档

**Comment by newlife201702** [comment]
我本地启动服务器后，访问http://localhost:3000/看不到页面

**Comment by noob3-3** [comment]
文档在哪里，没找到

**Comment by noob3-3** [comment]
看到文档链接了，感觉眼睛可以捐了😂
