### ISSUE TITLE
提示3000端口被占用

### ISSUE THREAD

**Issue by justincnn** [c121914yu/FastGPT#46]
一台全新配置的vps，系统为ubuntu 22.04，请问如何排查？谢谢

sudo lsof -i :3000
COMMAND  PID            USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
nginx   6010            root    6u  IPv4  44047      0t0  TCP *:3000 (LISTEN)
nginx   6038 systemd-resolve    6u  IPv4  44047      0t0  TCP *:3000 (LISTEN)
nginx   6039 systemd-resolve    6u  IPv4  44047      0t0  TCP *:3000 (LISTEN)

**Comment by c121914yu** [comment]
按标准流程排查。有可能是
nginx也监听了3000口，
