### ISSUE TITLE
Invalid character in header content ["auth"]

### ISSUE THREAD

**Issue by Kac001** [c121914yu/FastGPT#50]
发起对话时候提示Invalid character in header content ["auth"]
docker查看fastgpt日志：
<img width="1078" alt="image" src="https://github.com/c121914yu/FastGPT/assets/49395652/8af841e8-4bc5-4af5-bc2d-20ecc38779a0">

**Comment by Kac001** [comment]
用的第三方代理api
      - OPENAI_BASE_URL=https://api.openai-azure.com/v1

**Comment by c121914yu** [comment]
看常见问题

**Comment by Kac001** [comment]
已经解决，看了说明教程发现是
因为环境变量中，OPENAI_BASE_URL_AUTH 的中文没去掉，如果不需要这个变量，需要去掉
