### ISSUE TITLE
【help】CLAUDE的信息请问哪里可以获取？

### ISSUE THREAD

**Issue by justincnn** [c121914yu/FastGPT#52]
我的claude是通过slack对接的，在slack里找不到下面的信息：

CLAUDE_BASE_URL=calude模型请求地址
CLAUDE_KEY=CLAUDE_KEY

**Comment by c121914yu** [comment]
需要自己写一个接口服务

**Comment by c121914yu** [comment]
可以关注laf，他们社区会出接入教程。我是直接用laf实现的

**Comment by virgoone** [comment]
有laf接入的示例么 目前在laf上接入后对输出输入的结果有点不知道怎么处理
