### ISSUE TITLE
国外服务器拉取 FastGPT镜像总是失败

### ISSUE THREAD

**Issue by lsCoding666** [c121914yu/FastGPT#56]
```
Error response from daemon: Get "https://registry.cn-hangzhou.aliyuncs.com/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
已经配置了 dns 等。但是仍然失败。太难受了，能把镜像发布到 docker官方上吗？
https://blog.csdn.net/qq_35314762/article/details/82085864
这个方法试了
https://www.cnblogs.com/wangzy-Zj/p/16873237.html
这个也试了
死活不通。ping registry.cn-hangzhou.aliyuncs.com通
curl https://registry.cn-hangzhou.aliyuncs.com/v2/ 不通

**Comment by c121914yu** [comment]
😂之前国内一直拉不下docker io的。我看看能不能两边同步

**Comment by c121914yu** [comment]
可以直接拉git的镜像，事实更新main的

**Comment by yuanweize** [comment]
fastgpt-admin国外拉取太慢了,等了十多分钟还没好
    image: registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt-admin:latest
