### ISSUE TITLE
知识库导入文件问失败

### ISSUE THREAD

**Issue by DaZiYuan** [c121914yu/FastGPT#59]
三种方式都导入失败
![image](https://github.com/c121914yu/FastGPT/assets/80653/8bcd7e51-1ac8-4442-8ab1-81fd1dee7864)

![image](https://github.com/c121914yu/FastGPT/assets/80653/1255d3af-e098-4ce1-adcb-17a2836ac7e5)

![image](https://github.com/c121914yu/FastGPT/assets/80653/cfb42371-22b5-4b96-8649-2b26392adff7)

**Comment by c121914yu** [comment]
看后台日志

**Comment by DaZiYuan** [comment]
我用的https://fastgpt.run/怎么看日志?

**Comment by DaZiYuan** [comment]
小体验问题，没点左边+号就会出错。
![image](https://github.com/c121914yu/FastGPT/assets/80653/1b502a58-55a4-4d5e-8b7d-4d3c4607b1d8)
