### ISSUE TITLE
需求：文件导入记录

### ISSUE THREAD

**Issue by rainberg** [c121914yu/FastGPT#61]
需要可以查询哪些文件被成功导入了，哪些失败了

**Comment by c121914yu** [comment]
建议自己维护文件。线上数据可以手动修改，修改后与源文件可能不一致。

**Comment by c121914yu** [comment]
已增加记录来源，但不记录具体文件。
来源有3类值: 手动添加，手动修改，文件名。

可以根据文件名进行筛选。

**Comment by c121914yu** [comment]
完全一致的数据，导入时会被过滤掉。
