### ISSUE TITLE
修改完知识库的内容自动跳转到了第一页，不方便后续修改

### ISSUE THREAD

**Issue by XcNgg** [c121914yu/FastGPT#69]
V3.8.1
例如，修改知识库的第9页的内容，点击确认更改后，会自动跳转到知识库的第1页，没法继续修改当前页面的内容，需要重新翻页，如果知识库的量非常大的话修改起来会比较麻烦，建议考虑修改。

**Comment by c121914yu** [comment]
已修复该bug
