### ISSUE TITLE
bug:同名模型名在对话时会背同时选中

### ISSUE THREAD

**Issue by xiao-jay** [c121914yu/FastGPT#7]
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/87080562/231052381-5cc41ab1-5648-4072-b765-3df98b1e411c.png">
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/87080562/231052467-5c955a5c-cfb4-41ed-a3a7-c374aa57366a.png">

**Comment by c121914yu** [comment]
done
