### ISSUE TITLE
fastgpt 无法适配 azure openai embeddings 接口

### ISSUE THREAD

**Issue by Ye-Ting** [c121914yu/FastGPT#74]
fastgtp 在调用 embeddings 接口，input 参数采用是组数格式。[azure openai embeddings 接口 ](https://learn.microsoft.com/zh-cn/azure/cognitive-services/openai/reference#embeddings) input 只能支持 string 类型的数据。

希望得到修复，或者我可以通过 PR 提交修复。

盼回复。

**Comment by Ye-Ting** [comment]
代码运行起来之后，没有这个问题。

**Comment by c121914yu** [comment]
微软openai 接口会在后面几个小版本统一兼容
