### ISSUE TITLE
希望有对单个应用分享功能，只有分享出去建立的应用才有价值 

### ISSUE THREAD

**Issue by xiaganyu** [c121914yu/FastGPT#76]
![image](https://github.com/c121914yu/FastGPT/assets/10456594/4ef8792d-fd4c-4dd1-be9b-34f266a571c0)
分享出去的应用可以不用注册也能使用
没有建立应用和知识库的菜单，只能使用本应用

**Comment by c121914yu** [comment]
已经有这个功能。在应用详情里
