### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by MasterYFeng** [c121914yu/FastGPT#87]
1.对话引用的知识库词条可以增加删除词条功能
2.知识库中的词条可以增加批量删除功能
3.可以增加对知识库分类的功能
4.导出的CSV可以增加“来源”列
5.个人感觉没必要限制30分钟才能导出一次

**Comment by FaintGhost** [comment]
附议mdx或者其他文档累的文件能不能批量导入啊？想要导入上百个文档做embedding发现好像没有相关功能？

**Comment by c121914yu** [comment]
> 附议mdx或者其他文档累的文件能不能批量导入啊？想要导入上百个文档做embedding发现好像没有相关功能？

导入可以批量选择文件哇

**Comment by FaintGhost** [comment]
> > 附议mdx或者其他文档累的文件能不能批量导入啊？想要导入上百个文档做embedding发现好像没有相关功能？
> 
> 导入可以批量选择文件哇

我看了只能同一个目录下的，但是我下的文档是超多文件夹嵌套的那种， 好像不能直接选择文件夹？

**Comment by c121914yu** [comment]
> > > 附议mdx或者其他文档累的文件能不能批量导入啊？想要导入上百个文档做embedding发现好像没有相关功能？
> > 
> > 导入可以批量选择文件哇
> 
> 我看了只能同一个目录下的，但是我下的文档是超多文件夹嵌套的那种， 好像不能直接选择文件夹？

这个确实不行。。后面研究下，浏览器似乎没法跨目录选择。
可以写个小脚本，把它们搞到同一个目录

**Comment by MasterYFeng** [comment]
感谢作者大佬，希望项目越做越好！

**Comment by MasterYFeng** [comment]
> 1已经增加，在编辑框可以点删除。 2，感觉不是很有必要，目前删除没有确认按键，直接点删除比多选删除似乎更快。 3，在考虑交互。目前可以通过tag分类， 4，改天补上 5，没有用oss，带宽撑不住

感谢作者大佬，希望项目越做越好！
