### ISSUE TITLE
Invalid site key or not loaded in api.js: xxx

### ISSUE THREAD

**Issue by KingfuZhang** [c121914yu/FastGPT#89]
已经解决，google那2段没删除

**Comment by gotoolkits** [comment]
怎么解决的？我使用docker-compose启动的，也设置了CLIENT_GOOGLE_VER_TOKEN 和 SERVICE_GOOGLE_VER_TOKEN 但仍一直报“Invalid site key or not loaded in api.js: xxx” 错误。
