### ISSUE TITLE
希望添加设置自己的代理网址

### ISSUE THREAD

**Issue by qcl1234** [c121914yu/FastGPT#90]
希望可以填写自己的openai代理网址

**Comment by c121914yu** [comment]
环境变量可以配置，参考部署文档

**Comment by yhyu13** [comment]
https://doc.fastgpt.run/docs/installation/proxy/http_proxy/

其实用openai的base api 国内代理网站的api会更简单，这样fast gpt不需要指导代理的存在，国内代理api可以直连
