### ISSUE TITLE
希望强制按照知识库的原话回答，而不是自己总结

### ISSUE THREAD

**Issue by CyrusLiu158** [c121914yu/FastGPT#95]
在高相似度模式，发现他会总结知识库，而不是按照原话，经常会出现偏离。很痛苦，最好增加一种可选择的模式，谢谢~

**Comment by c121914yu** [comment]
模型问题，prompt解决。用GPT4效果最佳，模式也是 Prompt 。

**Comment by CyrusLiu158** [comment]
prompt怎么样提问，才可以严格按照原话呢，如果我让他扮演情感大师，然后严格按照知识库的原话回答，他还是自己总结。是在没找到好的方法，请指教，十分谢谢~~

**Comment by CyrusLiu158** [comment]
prompt怎么样提问，才可以严格按照原话呢，如果我让他扮演情感大师，然后严格按照知识库的原话回答，他还是自己总结。是在没找到好的方法，请指教，十分谢谢~~

**Comment by CyrusLiu158** [comment]
prompt怎么样提问，才可以严格按照原话呢，如果我让他扮演情感大师，然后严格按照知识库的原话回答，他还是自己总结。是在没找到好的方法，请指教，十分谢谢~~

**Comment by c121914yu** [comment]
prompt工程自己摸索~
